### ISSUE TITLE
GET Survey wo ich die PoiId mitgeben kann und alle Umfragen zu eine PoI kriege

### ISSUE THREAD

**Issue by MaximKirsch** [MaximKirsch/PartiBremen-API#14]

**Comment by NikitaHoffmann** [comment]
Ich sehe gerade das Survey bisher nicht mit einen poi kreatiert werden mussten ich füge das jetzt in POST hinzu.

**Comment by NikitaHoffmann** [comment]
Ich würde dann gerne wissen wir ihr das mit den surveys haben wollt:
wollt ihr das alle surveys einen attribute "poiId" haben oder sollen alle survey einer Poi zugewiesen werden?
Ich wundere mich da poi bereits einen Attribute mit einer liste für surveys hat.

**Comment by MaximKirsch** [comment]
Die Surveys haben in der DB schon ein Attribut poiId, das liegt daran, dass Springboot eine nicht das Objekt selber (Poi) in der Datenbank speichert sondern automatisch bloß eine Referenz daran speichert (poiId).
In Comment habe ich was ähnliches gemacht.
(Siehe Attribute)(Siehe CommentRepo)(siehe pma.partibremen.student.28apps-software.de)
